---
title: "Análise de Dados I @ DCX / CCAE / UFPB"
subtitle: "Prof. Marcus Carvalho"
---

Material da disciplina de Análise de Dados I

# Material das aulas

- [Apresentação da disciplina](1-introducao/0-apresentacao.qmd) (Slides)

## 1 Introdução

- [1.1 Introdução à análise de dados](1-introducao/1-introducao-ad.qmd) (Slides)
- [1.2 Introdução ao Python e Jupyter Notebook](1-introducao/2-intro-python-jupyter.qmd) (Atividade)
- [1.3 Introdução ao Pandas](1-introducao/3-intro-pandas.ipynb) (Notebook)
- [1.4 Exemplo com Pandas: análise de notas](1-introducao/4-exemplo-pandas.ipynb) (Notebook)
- [Laboratório 1: Manipulação de dados](https://github.com/analisededados-ufpb/lab-manipulacao-dados) (GitHub)

## 2 Análise Exploratória de Dados

- [2.1 Introdução à análise exploratória](2-eda/1-intro-eda.qmd) (Slides)
- [2.2 Estatística descritiva](2-eda/2-estatistica-descritiva.qmd) (Slides)
- [2.3 Análise de correlação](2-eda/3-correlacao.qmd) (Slides)
- [Laboratório 2: Análise Exploratória de Dados](https://github.com/analisededados-ufpb/lab-eda-imdb) (GitHub)

## 3 Regressão

- [3.1 Regressão linear simples](3-regressao/1-intro-regressao.qmd) (Slides)
- [3.2 Regressão linear múltipla](3-regressao/2-regressao-multipla.qmd) (Slides)
- [3.3 Regressão logística](3-regressao/3-regressao-logistica.qmd) (Slides)
- [Laboratório 3: Regressão](https://github.com/analisededados-ufpb/lab-regressao-eleicoes) (GitHub)

## 4 Inferência Estatística

- [4.1 Inferência Estatística](4-inferencia/1-intro-inferencia.qmd)


# Referências

- Bruce, P. et al. Estatística Prática para Cientistas de Dados. O’Reilly, 2020. Código e datasets: [https://github.com/gedeck/practical-statistics-for-data-scientists](https://github.com/gedeck/practical-statistics-for-data-scientists)

- McKinney, W. Python for Data Analysis, 3rd Edition, 2022. Disponível on-line: [https://wesmckinney.com/book/](https://wesmckinney.com/book/). [2a edição em português disponível na biblioteca do CCAE-UFPB]

- Grus, Joel. Data Science do Zero. Editora Alta Books, 2021. [Disponível na biblioteca virtual da UFPB (Minha Biblioteca)]

- Skienna, S. The Data Science Design Manual. Springer, 2017.

- VanderPlas, J. Python Data Science Handbook. 2022. Disponível em: [https://jakevdp.github.io/PythonDataScienceHandbook/](https://jakevdp.github.io/PythonDataScienceHandbook/)

- Wickhan, H. R for Data Science. Disponível em: [http://r4ds.had.co.nz](http://r4ds.had.co.nz)

- Downey, A. Think Stats - Exploratory Data Analysis in Python. 
